//
//  Author:
//    quentinlowery ${AuthorEmail}
//
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace FireEmblem
{
	public interface IEnemyBuilder
	{
		void setName();
		void setClass();
		void setLevel();
		void setHP();
		void setStrength();
		void setMagic();
		void setSkill();
		void setSpeed();
		void setLuck();
		void setDefense();
		void setResistance();
		void setMove();
		void setWeponRank();
		void setEquipment();
		void setSkills();
		
		Character getCharacter();
	}
}

